[package]
name = "expose-heartrate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arctic = "0.0.1"
websocket = "0.26.2"
futures = { version = "0.1" }
tokio = "1.17.0"
state = "0.5"

